// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA6wDKCS4dV5ykWZC1kKIsEyWzu6mSQZ0',
    appId: '1:890904511123:web:8d2f45958dce04c7698366',
    messagingSenderId: '890904511123',
    projectId: 'auth-app-4865b',
    authDomain: 'auth-app-4865b.firebaseapp.com',
    storageBucket: 'auth-app-4865b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkgaak3qEbuaE6ZmCgnhhD2ZUY0Q4iU98',
    appId: '1:890904511123:android:c0b9e864051828cc698366',
    messagingSenderId: '890904511123',
    projectId: 'auth-app-4865b',
    storageBucket: 'auth-app-4865b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-YHTKOwaJVDadbcyPhRNqZ_n30wwag7k',
    appId: '1:890904511123:ios:9b618023883b6c25698366',
    messagingSenderId: '890904511123',
    projectId: 'auth-app-4865b',
    storageBucket: 'auth-app-4865b.appspot.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-YHTKOwaJVDadbcyPhRNqZ_n30wwag7k',
    appId: '1:890904511123:ios:9b618023883b6c25698366',
    messagingSenderId: '890904511123',
    projectId: 'auth-app-4865b',
    storageBucket: 'auth-app-4865b.appspot.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA6wDKCS4dV5ykWZC1kKIsEyWzu6mSQZ0',
    appId: '1:890904511123:web:45a8d332acb942b3698366',
    messagingSenderId: '890904511123',
    projectId: 'auth-app-4865b',
    authDomain: 'auth-app-4865b.firebaseapp.com',
    storageBucket: 'auth-app-4865b.appspot.com',
  );
}
